from glob import glob

Import("env")

test_runner = env.Program(
    "test_runner",
    glob("*.cpp"),
    LIBPATH=["#src"],
    LIBS=["musicbrainz3", "cppunit"])

if env["PLATFORM"] == "win32":
    env.AddPostAction(test_runner,
        "cd src && %s && cd .." % (test_runner[0].abspath,))
else:
    env.AddPostAction(test_runner,
        "cd test && LD_LIBRARY_PATH=../src %s && cd .." % (test_runner[0].abspath,))
    
env.Alias("check", test_runner)
env.AlwaysBuild(test_runner)
    
env.DistSources(test_runner)
env.DistFiles(glob("*.h"))
env.DistFiles(Split("Makefile.am SConscript"))

