import sys
import os.path
Import('env')

dist_files = [
    'SConscript',
    'main.cpp',
    'read_file.h',
    'test_first.cpp',
    'test_model.cpp',
    'test_parser.cpp',
    'test_parser_artist.cpp',
    'test_parser_release.cpp',
    'test_parser_track.cpp',
    'test_parser_user.cpp',
    'test_utils.cpp',
    'test_ws_filters.cpp',
    'test_ws_includes.cpp',
    'test_ws.cpp',
    'test_disc.cpp'
    ]
    
sources = filter(lambda src: src.endswith('.cpp'), dist_files)

test = env.Program('test',
                   sources,
                   LIBPATH=['#src'],
                   LIBS=['musicbrainz3', 'cppunit'])

if sys.platform == 'win32':
    env.AddPostAction(test, "cd src && %s && cd .." % (test[0].abspath,))
else:
    env.AddPostAction(test, "cd test && LD_LIBRARY_PATH=../src %s && cd .." % (test[0].abspath,))
    
env.DistFiles(dist_files)

