from glob import glob

Import("env")
env = env.Copy()

env.Append(LIBPATH=["#src"])
env.Append(LIBS=["musicbrainz3"])

for source in glob("*.c") + glob("*.cpp"):
    example = env.Program(source.split(".")[0], [source])
    env.DistSources(example)

env.DistFiles(Split("Makefile.am SConscript"))

