Import('env')

env.Program("findartist", ["findartist.cpp"],
            LIBPATH=["#src"], LIBS=["musicbrainz3"])

env.Program("findtrack", ["findtrack.cpp"],
            LIBPATH=["#src"], LIBS=["musicbrainz3"])

env.Program("getartist_c", ["getartist.c"],
            LIBPATH=["#src"], LIBS=["musicbrainz3"])

