from glob import glob

Import("env")

includes = glob("*.h")

env.Alias("install", env.Install("$includedir/musicbrainz3", includes))

env.DistFiles(includes)
env.DistFiles(Split("Makefile.am SConscript"))

