INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(PKG_CPPUNIT cppunit)

FIND_PATH(CPPUNIT_INCLUDE_DIR cppunit/TestCase.h
    ${PKG_CPPUNIT_INCLUDE_DIRS}
    /usr/local/include
    /usr/include
)

FIND_LIBRARY(CPPUNIT_LIBRARIES cppunit
    ${PKG_CPPUNIT_LIBRARY_DIRS}
    /usr/local/lib
    /usr/lib
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(CppUnit DEFAULT_MSG CPPUNIT_LIBRARIES CPPUNIT_INCLUDE_DIR)
