from glob import glob

Import("env")
env = env.Copy()

env.Append(CPPDEFINES=['MB_API_EXPORTS'])

if env["PLATFORM"] == "win32":
    env.Append(LIBS=Split("advapi32 neon wsock32 discid winmm"))
else:
    env.Append(LIBS=Split("neon discid"))

musicbrainz3 = env.SharedLibrary(
    "musicbrainz3",
    glob("*.cpp") + glob("xmlParser/*.cpp"))

env.Alias("install", env.Install("$libdir", musicbrainz3))

env.DistSources(musicbrainz3)
env.DistFiles(glob("*.h"))
env.DistFiles(Split("Makefile.am SConscript"))

